apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tomcat-operator
  namespace: tomcat-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-operator
  namespace: tomcat-operator
spec:
  selector:
    matchLabels:
      app: tomcat-operator
  template:
    metadata:
      labels:
        app: tomcat-operator
    spec:
      serviceAccountName: tomcat-operator
      containers:
      - name: operator
        image: eu.gcr.io/adamsandor-test/tomcat-operator
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tomcat-operator-admin
subjects:
- kind: ServiceAccount
  name: tomcat-operator
  namespace: tomcat-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
