apiVersion: "sample.javaoperatorsdk/v1"
kind: WebPage
metadata:
  name: hellows
spec:
  html: |
    <html>
      <head>
        <title>Hello Operator World</title>
      </head>
      <body>
        Hello World! 2
      </body>
    </html>
