# Custom Resource Definition that will be used to generate the Java classes in target/generated-sources/java
# See https://github.com/fabric8io/kubernetes-client/blob/master/doc/java-generation-from-CRD.md
# The Java classes will then be used to recreate this CR in target/classes/META-INF/fabric8
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: leaderelection.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  names:
    kind: LeaderElection
    singular: leaderelection
    plural: leaderelection
    shortNames:
    - le
    - les
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              reconciledBy:
                items:
                  type: string
                type: array
            type: object
        type: object
    served: true
    storage: true
