#
# Copyright Java Operator SDK Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-processing-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-processing-operator
spec:
  selector:
    matchLabels:
      app: metrics-processing-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: metrics-processing-operator
    spec:
      serviceAccountName: metrics-processing-operator
      containers:
      - name: operator
        image: metrics-processing-operator
        imagePullPolicy: Never

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-processing-operator-admin
subjects:
- kind: ServiceAccount
  name: metrics-processing-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: metrics-processing-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-processing-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "sample.javaoperatorsdk"
  resources:
  - metricshandlingcustomresource1s
  - metricshandlingcustomresource1s/status
  - metricshandlingcustomresource2s
  - metricshandlingcustomresource2s/status
  verbs:
  - '*'

