# End to end integration test which deploys the Tomcat operator to a Kubernetes
# (Kind) cluster and creates custom resources to verify the operator's functionality
name: TomcatOperator End to End test
on:
   push:
      branches:
      - "*"
jobs: 
    tomcat_integration_test:
       runs-on: ubuntu-latest
       env:
        KIND_CL_NAME: e2e-test
       steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: clean resident local docker
          if: ${{ env.ACT }}
          continue-on-error: true
          run: |
            for DIMG in "$KIND_CL_NAME-control-plane "; do
              docker stop $DIMG ; docker rm $DIMG ;
            done ;
            sleep 1

        - name: Create Kubernetes KinD Cluster
          uses: container-tools/kind-action@v1.5.0
          with:
            cluster_name: e2e-test
            registry: false
  
        - name: Apply CRDs
          run: kubectl apply -f k8s/crd.yaml
          working-directory: sample-operators/tomcat-operator

        - name: Set up Java and Maven
          uses: actions/setup-java@v2
          with:
            java-version: 11
            distribution: adopt-hotspot
            cache: 'maven'

        - name: Build SDK
          run: mvn install -DskipTests

        - name: build jib
          working-directory: sample-operators/tomcat-operator
          run: |
            mvn --version
            mvn -B package jib:dockerBuild jib:buildTar -Djib-maven-image=tomcat-operator -DskipTests
            kind load image-archive target/jib-image.tar --name=${{ env.KIND_CL_NAME }}

        - name: Apply CRDs
          working-directory: sample-operators/tomcat-operator
          run: kubectl apply -f k8s/crd.yaml

        - name: Deploy Tomcat Operator
          working-directory: sample-operators/tomcat-operator
          run: |
            kubectl apply -f k8s/operator.yaml

        - name: Run E2E Tests
          working-directory: sample-operators/tomcat-operator
          run: mvn -B test -P end-to-end-tests

        - name: Dump state
          if: ${{ failure() }}
          run: |
            set +e
            echo "All namespaces"
            kubectl get ns
            echo "All objects in tomcat-operator"
            kubectl get all -n tomcat-operator -o yaml
            echo "Output of tomcat-operator pod"
            kubectl logs -l app=tomcat-operator -n tomcat-operator
            echo "All objects in tomcat-test"
            kubectl get deployment,pod,tomcat,webapp -n tomcat-test -o yaml
            echo "Output of curl command"
            kubectl logs curl -n tomcat-test
